spring:
  application:
    name: ToDoList
  datasource:
    url: jdbc:h2:mem:to-do-list
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
  h2:
    console:
      enabled: true
      path: /h2-console
jwt:
  expiration: ${JWT_EXPIRATION_TIME}
  secret: ${JWT_SECRET_KEY}
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
